#ifndef ERROR_INC
#define ERROR_INC
(*
 * Based on AST1, 250
 *)


#define OK 0
#define ERROR -1
#define EPERM -1
#define ENOENT -2
#define ESRCH -3
#define EBADF -9
#define EACCES -13
#define ENOTBLK -15
#define EEXIST -17
#define ENODEV -19
#define ENOTDIR -20
#define EISDIR -21
#define EINVAL -22
#define ENFILE -23
#define EMFILE -24
#define EFBIG -27
#define ENOSPC -28
#define EROFS -30
#define EMLINK -31
#define ESPIPE -32

#define E_LONG_STRING -103


#define E_OVERRUN -4
#define E_BAD_FCN -9
#define E_BAD_PROC -11
#define ENOTDIR -20


 #endif