(* 
 * param.inc based on param.h AST1, 7900
 *
 *)
#ifndef PARAM_INC
#define PARAM_INC

#define name m3^.m3p1
#define name1 m1^.m1p1
#define name1_length m1^.m1i1
#define name2 m1^.m1p2
#define mode m3^.m3i2
#define name_length m3^.m3i1
#define pathname m3^.m3cal

#define ls_fd m2^.m2i1
#define whence m2^.m2i2
#define offset m2^.m2l1

#define fd m1^.m1i1
#define buffer m1^.m1p1
#define fd m1^.m1i1
#define nbytes m1^.m1i2

(* Output message stuff *)
#define reply_type m1^.m_type


#endif 